apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{image}}
spec:
  selector:
    matchLabels:
      app: {{image}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{image}}
    spec:
      containers:
        - name: {{image}}
          image: {{image}}:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{targetPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{image}}
spec:
  ports:
    - protocol: "TCP"
      port: {{port}}        # The port inside the cluster
      targetPort: {{targetPort}}  # The port exposed by the service
  type: NodePort        # Type of service
  selector:
    app: {{image}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{image}}
  annotations:
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "/{{path}}"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/enable-cors: "true"
  namespace: default
spec:
  rules:
    - http:
        paths:
          - path: /{{path}}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{image}}
                port:
                  number: {{port}}